version: 2
jobs:
  build:
    working_directory: ~/honeysql
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps-1.10.3.933
    steps:
      - checkout
      - restore_cache:
          key: honeysql-{{ checksum "deps.edn" }}
      - run:
          name: Get rid of erroneous git config
          command: rm -rf ~/.gitconfig
      - run:
          name: Install Node
          command: sudo apt-get update && sudo apt-get install -y nodejs
      - run:
          name: Download Dependencies
          command: clojure -P -M:test:cljs-runner:eastwood:readme && clojure -P -M:1.9
      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
            - ~/node_modules
          key: honeysql-{{ checksum "deps.edn" }}
      - run:
          name: Run all the tests
          command: sh run-tests.sh all
